### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by jupiterbjy** [dancergraham/e57-python#28]
In pypi this is listed as MIT License but I don't see license file itself, should I be including license of e57 rust library's only?

I happened to include this library for company work so I think I should also include license to e57-python itself too but I'm not a lawyer, so I'm looking for your opinion.

**Comment by dancergraham** [comment]
Hello good question yes it is MIT licensed I will add a lessons file to the repo or feel free to open a pull request doing so!

**Comment by dancergraham** [comment]
OK - done, thanks for spotting the missing file! I'm interested in your experience using this library: 
* What do you like ?
* What features are particularly useful ?
* What was hard to do with it ?
* What features are missing ?

**Comment by jupiterbjy** [comment]
Oh that was fast! Thanks!

Annnd about usage I'm really sorry to let you down but I'm nowhere near professional nor company I work is! Wish I was some sort of professional LiDAR Surveyor to rate how nice your library is but nah I'm not such impressive person.

So my usage is extremely basic(almost prehistoric level) - all I do is just opening e57 format and reading & converting data in some other format. This library was extremely easy and handy for that.

To add a bit more detail - I have various pointcloud formats (`.laz` `.las` `.e57` etc) as input, then I unify format (i.e. axis, value range etc) & extract only data I need and export for other functionalities, mainly due to their large size messing up processing time.

can't directly share code (albeit honestly almost nothing in it tho) it roughly looks like this - nothing fancy
```py
class ImporterBase(ABC):
    """
    Base class for importer subclasses.
    Should perform normalization for Y up coordination system and 0~1 color range.
    """
    
    # File extension used for registering importer automatically,
    # So a single hash table search can find the right importer
    extension = ""

    @abstractmethod
    def __init__(self, path: pathlib.Path, center_xyz: bool = True):
        """Initializes importer with data path."""

        raise NotImplementedError

    @abstractmethod
    def __len__(self):
        """Returns the number of points in the data."""

        raise NotImplementedError

    @abstractmethod
    def fetch_xyz(self) -> Iterator[Sequence[float]]:
        """Fetches XYZ coordinates from data as Y-up coordination system."""

        raise NotImplementedError

    @abstractmethod
    def fetch_color(self) -> Iterator[Sequence[float]]:
        """Fetches RGB colors from data normalized to 0-1 range."""

        raise NotImplementedError

    def __iter__(self) -> Iterator[Tuple[Sequence[float], Sequence[float]]]:
        """Just some wrapper to Iterates over XYZ and RGB from data."""

        yield from zip(self.fetch_xyz(), self.fetch_color())
```
